version: '3'
services:
  web:
    image: nginx:1.8.1
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html #ここを作業ディレクトリに書き換え
  app:
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html #ここを作業ディレクトリに書き換え
  mysql:
    image: mysql:5.6.34
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass 
    ports:
      # 外部からアクセスする場合、ローカルにmysqlを入れているとポートが競合するので3306以外にしておく
      - "3308:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql